In [25]:
faqs = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [26]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [27]:
tokenizer = Tokenizer()

In [28]:
tokenizer.fit_on_texts([faqs])

In [29]:
tokenizer.word_index

{'the': 1,
 'you': 2,
 'i': 3,
 'to': 4,
 'a': 5,
 'of': 6,
 'is': 7,
 'have': 8,
 'will': 9,
 'what': 10,
 'can': 11,
 'course': 12,
 'program': 13,
 'for': 14,
 'sessions': 15,
 'in': 16,
 'be': 17,
 'and': 18,
 'this': 19,
 'if': 20,
 'all': 21,
 'am': 22,
 'pay': 23,
 'payment': 24,
 'on': 25,
 'we': 26,
 'do': 27,
 'subscription': 28,
 'where': 29,
 'make': 30,
 'rs': 31,
 'so': 32,
 'session': 33,
 'paid': 34,
 'join': 35,
 'able': 36,
 'placement': 37,
 'fee': 38,
 'month': 39,
 'not': 40,
 'get': 41,
 'yes': 42,
 'once': 43,
 'past': 44,
 'your': 45,
 'feb': 46,
 'assistance': 47,
 'data': 48,
 'monthly': 49,
 '7': 50,
 '5600': 51,
 'are': 52,
 'our': 53,
 'watch': 54,
 'google': 55,
 'by': 56,
 'com': 57,
 'mail': 58,
 'from': 59,
 'contact': 60,
 'us': 61,
 'at': 62,
 'or': 63,
 'website': 64,
 'doubt': 65,
 'science': 66,
 '799': 67,
 'total': 68,
 'duration': 69,
 'months': 70,
 'learning': 71,
 'case': 72,
 'part': 73,
 'see': 74,
 'late': 75,
 'dashboard': 76,
 'task': 77

In [30]:
# tokenizer.word_counts

In [31]:
# tokenizer.word_docs

In [32]:
# tokenizer.fit_on_sequences(faqs)

In [33]:
# tokenizer.word_index

In [34]:
len(tokenizer.word_counts)

277

In [35]:
len(tokenizer.word_index)

277

In [45]:
input_sequences=[]
for sentence in faqs.split('\n'):
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]
#     print(sentence)
    print(tokenizer.texts_to_sequences([sentence])[0])
    for i in range(1,len(tokenized_sentence)):
        input_sequences.append(tokenized_sentence[:i+1])
        

[89, 1, 13]
[10, 7, 1, 12, 38, 14, 48, 66, 90, 13, 142, 143]
[1, 12, 91, 5, 49, 28, 92, 29, 2, 8, 4, 30, 49, 93, 6, 31, 67, 39]
[10, 7, 1, 68, 69, 6, 1, 12]
[1, 68, 69, 6, 1, 12, 7, 50, 70, 32, 1, 68, 12, 38, 144, 67, 50, 31, 51, 145]
[10, 7, 1, 146, 6, 1, 90, 13]
[26, 9, 17, 147, 1, 148, 149]
[94, 150]
[94, 151, 14, 48, 66]
[48, 152]
[153, 14, 48, 66]
[154, 14, 155, 71]
[95, 156]
[157, 95]
[158]
[72, 96]
[9, 97, 71, 18, 98, 17, 5, 73, 6, 19, 13]
[99, 98, 18, 97, 71, 159, 52, 40, 5, 73, 6, 19, 160, 161]
[10, 20, 3, 100, 5, 101, 33, 9, 3, 41, 5, 102, 6, 1, 33]
[42, 21, 53, 15, 52, 162, 32, 103, 20, 2, 100, 5, 33, 2, 11, 163, 164, 18, 54, 1, 102]
[29, 11, 3, 165, 1, 104, 166]
[167, 19, 55, 168, 4, 74, 39, 56, 39, 105, 169, 6, 1, 12, 170, 171, 55, 57, 172, 173, 174, 175, 176, 177, 178]
[10, 7, 1, 105, 69, 6, 21, 1, 101, 15]
[179, 21, 1, 15, 180, 106, 181]
[10, 7, 1, 182, 183, 56, 1, 184, 185, 1, 15]
[186]
[107, 9, 3, 17, 187, 89, 1, 188, 104]
[2, 9, 41, 5, 58, 59, 53, 189, 190, 191, 34, 3

In [42]:
input_sequences

[[89, 1],
 [89, 1, 13],
 [10, 7],
 [10, 7, 1],
 [10, 7, 1, 12],
 [10, 7, 1, 12, 38],
 [10, 7, 1, 12, 38, 14],
 [10, 7, 1, 12, 38, 14, 48],
 [10, 7, 1, 12, 38, 14, 48, 66],
 [10, 7, 1, 12, 38, 14, 48, 66, 90],
 [10, 7, 1, 12, 38, 14, 48, 66, 90, 13],
 [10, 7, 1, 12, 38, 14, 48, 66, 90, 13, 142],
 [10, 7, 1, 12, 38, 14, 48, 66, 90, 13, 142, 143],
 [1, 12],
 [1, 12, 91],
 [1, 12, 91, 5],
 [1, 12, 91, 5, 49],
 [1, 12, 91, 5, 49, 28],
 [1, 12, 91, 5, 49, 28, 92],
 [1, 12, 91, 5, 49, 28, 92, 29],
 [1, 12, 91, 5, 49, 28, 92, 29, 2],
 [1, 12, 91, 5, 49, 28, 92, 29, 2, 8],
 [1, 12, 91, 5, 49, 28, 92, 29, 2, 8, 4],
 [1, 12, 91, 5, 49, 28, 92, 29, 2, 8, 4, 30],
 [1, 12, 91, 5, 49, 28, 92, 29, 2, 8, 4, 30, 49],
 [1, 12, 91, 5, 49, 28, 92, 29, 2, 8, 4, 30, 49, 93],
 [1, 12, 91, 5, 49, 28, 92, 29, 2, 8, 4, 30, 49, 93, 6],
 [1, 12, 91, 5, 49, 28, 92, 29, 2, 8, 4, 30, 49, 93, 6, 31],
 [1, 12, 91, 5, 49, 28, 92, 29, 2, 8, 4, 30, 49, 93, 6, 31, 67],
 [1, 12, 91, 5, 49, 28, 92, 29, 2, 8, 4, 30, 49, 93, 6

In [50]:
max_len = max([len(x) for x in input_sequences])
max_len

57

In [51]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [53]:
padded_input_sequence = pad_sequences(input_sequences,max_len,padding='pre')

In [54]:
X = padded_input_sequence[:,:-1]
y=padded_input_sequence[:,-1]

In [55]:
y

array([  1,  13,   7,   1,  12,  38,  14,  48,  66,  90,  13, 142, 143,
        12,  91,   5,  49,  28,  92,  29,   2,   8,   4,  30,  49,  93,
         6,  31,  67,  39,   7,   1,  68,  69,   6,   1,  12,  68,  69,
         6,   1,  12,   7,  50,  70,  32,   1,  68,  12,  38, 144,  67,
        50,  31,  51, 145,   7,   1, 146,   6,   1,  90,  13,   9,  17,
       147,   1, 148, 149, 150, 151,  14,  48,  66, 152,  14,  48,  66,
        14, 155,  71, 156,  95,  96,  97,  71,  18,  98,  17,   5,  73,
         6,  19,  13,  98,  18,  97,  71, 159,  52,  40,   5,  73,   6,
        19, 160, 161,  20,   3, 100,   5, 101,  33,   9,   3,  41,   5,
       102,   6,   1,  33,  21,  53,  15,  52, 162,  32, 103,  20,   2,
       100,   5,  33,   2,  11, 163, 164,  18,  54,   1, 102,  11,   3,
       165,   1, 104, 166,  19,  55, 168,   4,  74,  39,  56,  39, 105,
       169,   6,   1,  12, 170, 171,  55,  57, 172, 173, 174, 175, 176,
       177, 178,   7,   1, 105,  69,   6,  21,   1, 101,  15,  2

In [56]:
X

array([[  0,   0,   0, ...,   0,   0,  89],
       [  0,   0,   0, ...,   0,  89,   1],
       [  0,   0,   0, ...,   0,   0,  10],
       ...,
       [  0,   0,   0, ...,   0, 274,  25],
       [  0,   0,   0, ..., 274,  25, 275],
       [  0,   0,   0, ...,  25, 275, 276]])

In [57]:
#we will use multiclass classification

In [58]:
#we will transform output with one hot encoded like ex - [0,0,0,0,1,0,0,0] 

In [59]:
X.shape

(825, 56)

In [60]:
y.shape

(825,)

In [61]:
from tensorflow.keras.utils import to_categorical



In [63]:
y = to_categorical(y,num_classes=278)
#since tokenizer.word_index not starting from 0 , that's why 277+1

In [62]:
len(tokenizer.word_index)

277

In [64]:
y


array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [65]:
y.shape

(825, 278)

In [66]:
X.shape

(825, 56)

In [67]:
#first layer embedding , then LSTM layer , softmax dense layer 

In [68]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [75]:
model = Sequential()

model.add(Embedding(278,100,input_length=56))
model.add(LSTM(150))
model.add(Dense(278,activation='softmax'))

In [76]:
# X

In [77]:
# y

In [78]:
X.shape,y.shape

((825, 56), (825, 278))

In [80]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [81]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 56, 100)           27800     
                                                                 
 lstm (LSTM)                 (None, 150)               150600    
                                                                 
 dense (Dense)               (None, 278)               41978     
                                                                 
Total params: 220378 (860.85 KB)
Trainable params: 220378 (860.85 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [82]:
model.fit(X,y,epochs=100)

Epoch 1/100
26/26 [==============================] - 6s 90ms/step - loss: 5.4366 - accuracy: 0.0703
Epoch 2/100
26/26 [==============================] - 2s 93ms/step - loss: 5.0788 - accuracy: 0.0788
Epoch 3/100
26/26 [==============================] - 2s 80ms/step - loss: 5.0055 - accuracy: 0.0788
Epoch 4/100
26/26 [==============================] - 2s 77ms/step - loss: 4.9688 - accuracy: 0.0788
Epoch 5/100
26/26 [==============================] - 2s 76ms/step - loss: 4.9283 - accuracy: 0.0788
Epoch 6/100
26/26 [==============================] - 2s 79ms/step - loss: 4.8610 - accuracy: 0.0788
Epoch 7/100
26/26 [==============================] - 2s 81ms/step - loss: 4.7239 - accuracy: 0.0861
Epoch 8/100
26/26 [==============================] - 2s 85ms/step - loss: 4.5285 - accuracy: 0.1164
Epoch 9/100
26/26 [==============================] - 2s 90ms/step - loss: 4.3155 - accuracy: 0.1539
Epoch 10/100
26/26 [==============================] - 2s 73ms/step - loss: 4.0747 - accuracy: 0.2000

26/26 [==============================] - 2s 69ms/step - loss: 0.1552 - accuracy: 0.9467
Epoch 83/100
26/26 [==============================] - 2s 72ms/step - loss: 0.1534 - accuracy: 0.9467
Epoch 84/100
26/26 [==============================] - 2s 73ms/step - loss: 0.1517 - accuracy: 0.9491
Epoch 85/100
26/26 [==============================] - 2s 69ms/step - loss: 0.1505 - accuracy: 0.9455
Epoch 86/100
26/26 [==============================] - 2s 69ms/step - loss: 0.1484 - accuracy: 0.9467
Epoch 87/100
26/26 [==============================] - 2s 70ms/step - loss: 0.1453 - accuracy: 0.9491
Epoch 88/100
26/26 [==============================] - 2s 69ms/step - loss: 0.1442 - accuracy: 0.9515
Epoch 89/100
26/26 [==============================] - 2s 70ms/step - loss: 0.1425 - accuracy: 0.9467
Epoch 90/100
26/26 [==============================] - 2s 69ms/step - loss: 0.1421 - accuracy: 0.9479
Epoch 91/100
26/26 [==============================] - 2s 70ms/step - loss: 0.1410 - accuracy: 0.9479
Epo

In [83]:
text = "mail"

In [84]:
#tokenize , #padding , #predict

In [89]:
token_Text = tokenizer.texts_to_sequences([text])[0]

padded_text = pad_sequences([token_Text],maxlen=56,padding='pre')

In [94]:
len(padded_text[0])

56

In [101]:
predicted = model.predict(padded_text)

1/1 [==============================] - 0s 42ms/step


In [102]:
import numpy as np

In [105]:
pos = np.argmax(predicted)

In [104]:
predicted

array([[7.64990182e-06, 4.54669731e-04, 2.58607026e-02, 9.57012409e-04,
        7.07570166e-07, 1.90217304e-03, 1.55137823e-05, 1.18694259e-02,
        3.33772204e-03, 1.26474397e-03, 1.08463311e-04, 2.48782308e-04,
        1.86291861e-03, 9.86058731e-04, 2.42861565e-02, 2.91657215e-03,
        1.00643374e-05, 3.27859377e-03, 1.08376304e-02, 5.36483945e-04,
        4.81104217e-02, 3.74929653e-03, 2.28768978e-02, 4.52608307e-04,
        5.00689348e-05, 4.86012141e-04, 1.13017512e-02, 5.42873633e-04,
        7.73051652e-05, 3.32030992e-04, 2.07048288e-05, 1.63243443e-04,
        1.94053195e-04, 1.93125543e-05, 8.21917001e-06, 1.81660827e-04,
        5.42248781e-05, 4.07540612e-03, 9.57425043e-04, 1.47700054e-03,
        4.80855932e-04, 8.36718711e-04, 4.12345298e-06, 6.60632774e-02,
        3.37946782e-04, 8.31496436e-05, 7.64474506e-03, 2.21765484e-03,
        4.88093495e-03, 1.92572630e-03, 4.54036240e-03, 6.05338028e-05,
        4.02537989e-04, 4.30679601e-03, 8.24564049e-05, 5.957923

In [107]:
for word,index in tokenizer.word_index.items():
    if index==pos:
        print(word)

algorithms


In [113]:
text = "himanshu"
for i in range(5):
    token_Text = tokenizer.texts_to_sequences([text])[0]

    padded_text = pad_sequences([token_Text],maxlen=56,padding='pre')
    predicted = model.predict(padded_text)
    pos = np.argmax(predicted)
    for word,index in tokenizer.word_index.items():
        if index==pos:
            text=text+" "+word
            print(text)
    

1/1 [==============================] - 0s 44ms/step
himanshu registration
1/1 [==============================] - 0s 49ms/step
himanshu registration queries
1/1 [==============================] - 0s 46ms/step
himanshu registration queries not
1/1 [==============================] - 0s 45ms/step
himanshu registration queries not a
1/1 [==============================] - 0s 42ms/step
himanshu registration queries not a part


In [115]:
#hyperparamter tuning in model to increase stacked lstm,bidirectional lstm , transformers

In [117]:
tf.keras.models.save_model(model,'model.h5')

C:\Users\mrhim\AppData\Local\Temp\ipykernel_3184\2233621448.py:1: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  tf.keras.models.save_model(model,'model.h5')
